[tool.poetry]
name = "100daysofcode"
version = "0.1.0"
description = "Coding for 100 days"
authors = ["DaniRaouf7 <danishraouf@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
